### ISSUE TITLE
Feature request: include CI files

### ISSUE THREAD

**Issue by Ben-PH** [jessebraham/esp-template#95]
I've started a project based on generating from this template, and setting up CI would be made easier if the generated files included some CI. This is what I've put together for my project:

```yml
name: check

on:
  pull_request:
    branches:
      - main


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
      - uses: Swatinem/rust-cache@v2

      - name: check rustfmt
        run: cargo fmt -- --check --color always

      - name: clippy
        run: cargo clippy -- -D warnings
```

the steps were partially based on the CI files for this repo.

If there's a way to bring in the right toolchain in a way that is nice and quick, and only sets things up for the appropriate platform (I'm using `S3`, but I notice work is being done to setup for non `S3` platforms), that would probably be ideal.
